### ISSUE TITLE
add remote desktop awareness support (libRDA)

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-session#13]
the session indicator could behave differently, if the session is run remotely e.g. via X2Go. For this, libRDA [1] should be used.

[1] https://github.com/ArcticaProject/librda

**Comment by tari01** [comment]
@sunweaver 

1. Is there an environment variable (or something else?) we can probe to determine whether we are being run remotely?
2. Could you please list the menu changes this would involve?
