### ISSUE TITLE
Building tests fails

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/ayatana-indicator-session#17]
When building with **-Denable_tests=ON**:

```
[ 17%] Generating gschemas.compiled
cp: '/home/tari/build/ayatana-indicator-session/tests/org.ayatana.indicator.session.backendmock.gschema.xml' and '/home/tari/build/ayatana-indicator-session/tests/org.ayatana.indicator.session.backendmock.gschema.xml' are the same file
cp: '/home/tari/build/ayatana-indicator-session/tests/org.ayatana.indicator.session.gschema.xml' and '/home/tari/build/ayatana-indicator-session/tests/org.ayatana.indicator.session.gschema.xml' are the same file
cp: '/home/tari/build/ayatana-indicator-session/tests/org.gnome.desktop.lockdown.gschema.xml' and '/home/tari/build/ayatana-indicator-session/tests/org.gnome.desktop.lockdown.gschema.xml' are the same file
cp: '/home/tari/build/ayatana-indicator-session/tests/org.gnome.settings-daemon.plugins.media-keys.gschema.xml' and '/home/tari/build/ayatana-indicator-session/tests/org.gnome.settings-daemon.plugins.media-keys.gschema.xml' are the same file
make[2]: *** [tests/CMakeFiles/gschemas-compiled.dir/build.make:84: tests/gschemas.compiled] Error 1
make[1]: *** [CMakeFiles/Makefile2:481: tests/CMakeFiles/gschemas-compiled.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```
**cp** should remove the target first

**Comment by sunweaver** [comment]
@tari01: Wouldn't it be a better solution making sure that the files don't exist before you want to copy them to the location (e.g. in some clean rule?)? Why is the file already in its destination location at all?

**Comment by tari01** [comment]
@sunweaver: It's a CMake bug: it is trying to copy **tests/*gschema.xml** to **tests**, i.e to itself. The change in the PR does exactly what you say: no copying if the file exist.

**Comment by sunweaver** [comment]
> @sunweaver: It's a CMake bug: it is trying to copy tests/*gschema.xml to **tests**, i.e to itself. The change in the PR does exactly what you say: no copying if the file exist.

Hmmm... I looked at things more closely. The ayatana-indicator-session does an out-of-source build, so all build results end up in the obj-<multiarch>/ subfolder. For the .schema files, I'd suggest that those get copied into obj-<multiarch>/ and get used from there.

From what I see with from rest of the build flow of this project, nothing gets changed in the source tree. So, copying files from the source tree to the source tree is a bug in itself. We should copy from the source tree to the binary tree and use the files from there.

Am I to picky on this one?

**Comment by tari01** [comment]
Picky is good. Yields quality results.

Building outside the source tree works fine. The problem is with in-place builds. When testing stuff, I always create both - in the beginning when I first packaged Ayatana, it proved necessary, because we had a cmake/autogen mess with loads of build errors, so I always picked the one that hurt the least. Now it's just a habit.

The question is then, do we support in-place builds, or force people to build out-of-source (in which case I retract my bug report)?

**Comment by tari01** [comment]
All our CMake builds now work fine out-of-source. No need for in-place building. Closing.
