### ISSUE TITLE
Show real name on panel doesn't work

### ISSUE THREAD

**Issue by zippy-zebu** [AyatanaIndicators/ayatana-indicator-session#3]
I am using it on ubuntu mate. If I set show-real-name from dconf, it doesn't work.

**Comment by zippy-zebu** [comment]
I found this on launchpad bug https://bugs.launchpad.net/ubuntu/+source/indicator-session/+bug/1640409

Debian unsets XDG_SEAT and XDG_SESSION_ID /etc/X11/Xsession.d/95dbus_update-activation-env. I commented out those & it started working. But it shows user name instead of real name.

**Comment by tari01** [comment]
@zippy-zebu, @sunweaver 

I cannot replicate this on Arch. Is this still an issue in Debian?

**Comment by sunweaver** [comment]
I can neither replicate this on Ubuntu MATE 20.04. Thus, closing.

**Comment by zippy-zebu** [comment]
@sunweaver I can still reproduce this on Ubuntu mate 20.04. Also on mate session I don't have XDG_SEAT and XDG_SESSION_ID variable set.

**Comment by sunweaver** [comment]
@zippy-zebu: please note that Ubuntu MATE 20.04 is still on Ubuntu Indicators. Please checkout this video by @flexiondotorg how live-streamed a switch-over from Ubuntu Indicators to Ayatana Indicators for upcoming Ubuntu MATE 20.10.

https://www.youtube.com/watch?v=4ICRjjjMbEE
