### ISSUE TITLE
debian/control: Settings daemon missing from "Depends" in published package

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/ayatana-indicator-session#68]
https://salsa.debian.org/debian-ayatana-team/ayatana-indicator-session/-/blob/master/debian/control

is missing `gnome-settings-daemon | mate-settings-daemon | xfce4-settings,`

This forces us to install `gnome-settings-daemon` manually on Lomiri.

**Comment by sunweaver** [comment]
It was agreed that the settings daemon should be pulled in via the desktop env, not via a system indicator.
