### ISSUE TITLE
session indicator in Lomiri dies if gnome-settings-daemon-common bin:pkg is not installed

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-session#79]
As Lomiri does not need gnome-settings-daemon-*, we should allow for the session indicator to launch without that gsettings schema to be installed.

**Comment by peat-psuwit** [comment]
Should be fixed by #78?

**Comment by sunweaver** [comment]
> Should be fixed by #78?

Probably. Closing for now.
